services:
  photonpiano.database:
    image: postgres:15
    container_name: photonpiano.database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PhotonPiano
    volumes:
    - ./.container/photonpiano-db:/var/lib/postgresql/data
    ports:
    - "5432:5432"


  photonpiano.api:
    image: ${DOCKER_REGISTRY-}photonpianoapi
    container_name: photonpiano.api
    restart: on-failure
    depends_on:
      - photonpiano.cache
    build:
      context: .
      dockerfile: PhotonPiano.Api/Dockerfile
    ports:
       - "5000:5000"
       - "5001:5001"
    environment:
         - ASPNETCORE_ENVIRONMENT=Production
         - ASPNETCORE_URLS=http://+:5000
         - OTEL_EXPORTER_OTLP_ENDPOINT=http://photonpiano-jaeger:4317
    pull_policy: always
  
      
#  photonpiano.cache:
#    image: redis:6.2
#    restart: always
#    container_name: photonpiano.cache
#    ports:
#      - "6379:6379"
#
#  photonpiano.jaeger:
#    image: jaegertracing/all-in-one:latest
#    container_name: photonpiano.jaeger
#    environment:
#      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
#    ports:
#      - "4317:4317"
#      - "16686:16686"     # UI port
